import pygame as pg
import grafico.recursos.color as color

MIN_WIDTH, MIN_HEIGHT = 1280, 720
WIDTH_ORIGINAL, HEIGHT_ORIGINAL = 1920, 1080
WIDTH, HEIGHT = 1280, 720
SURFACE = pg.display.set_mode((WIDTH, HEIGHT), pg.RESIZABLE)

SCALE = 0.67

VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH = 0, 4, 0

'''
EL PATCH ES LA CANTIDAD DE VECES QUE SE HA MODIFICADO EL CODIGO

VERSION 0.0
IMPLEMENTACION DE LAS REGLAS DE JUEGO Y SE VISUALIZA EL PROCESO DESDE LA TERMINAL

VERSION 0.1 
INCLUYE BUSCADOR DE ANAGRAMAS

VERSION 0.2
INCLUYE INTERFAZ GRAFICA E IMPLEMENTACION DE LA VERSION 0.0

VERSION 0.3
INCLUYE INTERACCION CON LA BASE DE DATOS EN LINEA EN EL SERVER JOOKEEZ.COM

VERSION 0.4
LOS PANELES DE JUEGO YA MUESTRAN LA INFORMACION AGREGADA EN LA BASE DE DATOS
'''

FPS = 60
TIPOGRAFIA = 'Militech.ttf'
PANTALLA = 'inicio'

SIZE_INFO = 48
Y_INFO = 979
DY_INFO = 67
BORDE_RADIO_INFO = 30
GROSOR_BORDE_INFO = 2
COLOR_TEXTO_INFO = color.AMARILLO

PADDING_INFO = 120
SIZE_TIEMPO = 155
PADDING_RIGHT_INFO = 15
PADDING_BOTTOM_INFO = 34
SIZE_PUNTAJE_PARTICIPANTE = 86
SIZE_CANTIDAD = 85
SIZE_CANTIDAD_PADDING = 1
SIZE_PISTA = 0
SIZE_TOTAL_INFO =  0

X_LETRAS, Y_LETRAS = 125, 165
SIZE_LETRA = 116
BORDE_RADIO_LETRA = 9
GROSOR_BORDE_LETRA = 2
COLOR_TEXTO_LETRA = color.AMARILLO
PADDING_X_LETRA = 15
PADDING_Y_LETRA = 200
CANTIDAD_FILAS_ALFAGRAMA = 2
CANTIDAD_FILAS_ALFAGRAMA_RESUELTO = 3
CANTIDAD_FILAS_ANAGRAMA = 1
ESCALADO_ESPACIADO = 0.25
MAXIMO_LETRAS_FILA = 18

X_LETRAS_SMALL, Y_LETRAS_SMALL = 90, 120
SIZE_LETRA_SMALL = 8620
PADDING_X_LETRA_SMALL = 8
PADDING_Y_LETRA_SMALL = 25

X_LETRAS_XSMALL, Y_LETRAS_XSMALL = 67.5, 90
SIZE_LETRA_XSMALL = 65
PADDING_X_LETRA_XSMALL = 6
PADDING_Y_LETRA_XSMALL = 20

X_BOTON, Y_BOTON = 300, 70
SIZE_BOTON = 58
PADDING_X_BOTON = 10
PADDING_Y_BOTON = 10

COLOR_PARTICIPANTES = [color.BORDE_ROJO, color.BORDE_NARANJO, color.BORDE_VERDE, color.BORDE_CELESTE]

LOGIN_USUARIO = "jookeez"
PASSWD_USUARIO = "jkz"
PASSWD_USUARIO_OCULTA = ""
DATOS_INCORRECTOS = False
TIPO_USUARIO = ""
TIPOS_DE_USUARIOS = ["Administrador", "Moderador", "Editor"]
MAXIMO_LETRAS_USERNAME = 12

NUEVO_TIPO_USUARIO = ""
PALABRA_CLAVE = "***"
PALABRA_CLAVE_OCULTA = "***"
CLAVE_NUEVA = "***"
CLAVE_NUEVA_OCULTA = "***"
REPETIR_CLAVE_NUEVA = "***"
REPETIR_CLAVE_NUEVA_OCULTA = "***"

DX_MENU = 510

PANEL_MOSTRADO = "login"
MENU_PRINCIPAL = ["crear_palabras", "crear_panel", "crear_partida", "home", "reglas", "creditos", "datos_usuario"]

PANEL_REGLAS = "r_palabra_anagrama"
MENU_REGLAS = ["r_palabra_anagrama", "r_contrarreloj", "r_frase_alfagrama", "r_contrarreloj_multiple", "r_criptocodigo"]

PANEL_CREAR = "default"
MENU_CREAR_PANELES = ["cp_palabra_anagrama", "cp_contrarreloj", "cp_frase_alfagrama", "cp_contrarreloj_multiple", "cp_criptocodigo"]

MENU_PANELES = ["p_palabra_anagrama", "p_contrarreloj", "p_frase_alfagrama", "p_contrarreloj_multiple", "p_criptocodigo"]
LISTADO_PANELES = ["Palabra anagrama", "Frase alfagrama", "Contrarreloj", "Palabra anagrama", "Frase alfagrama", "Contrarreloj múltiple", "Criptocódigo"]
ID_LISTADO_PANELES = ["13", "3", "1", "9", "2", "10", "2"]

PALABRA_BUSCADA = ""
CANTIDAD_LETRAS_PALABRA_BUSCADA = len(PALABRA_BUSCADA)
ALFAGRAMA_GENERADO = ""
ANAGRAMAS_ENCONTRADOS = ""
CANTIDAD_COINCIDENCIAS = 0
TIEMPO_BUSQUEDA = 0.0
TIEMPO_ESTIMADO_BUSQUEDA = ""
ESTIMADO_BUSQUEDA = [0.01, 0.01, 0.01, 0.03, 0.14, 0.22, 7.09, 26.08, 267.09]

TEXTO_ACTIVO = ""
PANEL_ACTIVO = 0
MAXIMO_LETRAS_TEXT_AREA = 50
MAXIMO_LETRAS_ID = 3
EXCEPCION_TEXTO_CREAR_PALABRA = ""
CANTIDAD_CONTRARRELOJ_MULTIPLE = 0
ID_CONTRARRELOJ_MULTIPLE = 0

CONTENIDO_CREAR_PANEL = [["0", "", ""], ["0"], ["0", "", ""],["0", "", ""],["0", "", "", "", "", ""]]
ID_CONTRARRELOJ = 0
CONTENIDO_CONTRARRELOJ = [[0, "", "", ""],[1, "", "", ""],[2, "", "", ""],[3, "", "", ""],[4, "", "", ""],[5, "", "", ""],[6, "", "", ""],[7, "", "", ""],[8, "", "", ""],[9, "", "", ""],[10, "", "", ""],[11, "", "", ""],[12, "", "", ""],[13, "", "", ""],[14, "", "", ""]]

CONTENIDO_DATOS_PANEL = {}